"""Chat id string

Revision ID: 15ca23e67c63
Revises: c2ee49c1c62f
Create Date: 2019-12-30 23:57:31.115668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ca23e67c63'
down_revision = 'c2ee49c1c62f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='unique')
    # ### end Alembic commands ###
