"""Fix chats

Revision ID: 52f0f0a78a96
Revises: a8bfb6b55e43
Create Date: 2019-12-30 20:26:02.789744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f0f0a78a96'
down_revision = 'a8bfb6b55e43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chat', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat', type_='unique')
    # ### end Alembic commands ###
