"""Unique entry link

Revision ID: a8bfb6b55e43
Revises: 4fb4771492f9
Create Date: 2019-12-30 20:17:23.866057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8bfb6b55e43'
down_revision = '4fb4771492f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'entry', ['link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='unique')
    # ### end Alembic commands ###
