"""Added chat name

Revision ID: c2ee49c1c62f
Revises: d7e1d49ca4a8
Create Date: 2019-12-30 22:25:38.519575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ee49c1c62f'
down_revision = 'd7e1d49ca4a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat', 'name')
    # ### end Alembic commands ###
