"""Added tg_operation in user

Revision ID: d7e1d49ca4a8
Revises: 1599fb1ab2fa
Create Date: 2019-12-30 22:02:28.495214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7e1d49ca4a8'
down_revision = '1599fb1ab2fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tg_operation', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'tg_operation')
    # ### end Alembic commands ###
